### ISSUE TITLE
error

### ISSUE THREAD

**Issue by abdalmajid77** [baum1810/ipgrabber#1]
bx7@LAPTOP-D82F1NJI:~/ipgrabber$ python main.py
  File "main.py", line 12
    city = requests.get(f'https://ipapi.co/{publicip}/city').text
                                                          ^
SyntaxError: invalid syntax

**Comment by baum1810** [comment]
no idea how you got that error i didnt got that error maybe you edited something or deleted something for me it works fine without any error

**Comment by baum1810** [comment]
i also recoded it so there is a new version maybe that one works for you so just redownload the code and try it out and let me know if you still have any errors
